baseURL: "https://ofonime.netlify.app"
languageCode: "en-us"
title: "Ofonime's Ramble"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
